### ISSUE TITLE
Is is possible to run YTuner as linux service?

### ISSUE THREAD

**Issue by seldam** [coffeegreg/YTuner#13]
I have made a linux service on a raspberry pi. But it looks like this is not working. YTuner is running but not working correctly. When I run YTuner from the command line it does work correctly. Also tried running it from a cronjob @reboot, also not working.

**Comment by coffeegreg** [comment]
Have you started this service with the appropriate permissions to listen on TCP port 80 and UDP port 53?
Try to run `ytuner` as a service with redirect `stdout` to simple log file with `> YTunerLogFile.txt` and check this file out.

**Comment by coffeegreg** [comment]
Please let me know about the model of your AVR that YTuner works with.
This allow me to continue adding AVRs to the `Confirmed working` list.

**Comment by seldam** [comment]
Model: RX-V675
The YTuner service runs fine now. But there are still some issues

IP: 192.168.178.2
Default gateway (first try): 192.168.178.1 (internet router ip) -> streams are working (fetch stations from YTuner is not working)
Default gateway (second try) : 192.168.178.3 (YTuner) -> streams are not working (fetch stations from Ytuner is working)
DNS1: 192.168.178.3 (YTuner)
DNS2: 192.168.178.3 (YTuner)

**Comment by TheBossME** [comment]
Here is my ytuner.service setup.

[Unit]
Description=ytuner radio service
Wants=network-online.target
BindsTo=keepalived.service
After=keepalived.service
StopWhenUnneeded=true

[Service]
User=root
Group=root
ExecStart=/opt/ytuner/ytuner
WorkingDirectory=/opt/ytuner
StandardOutput=file:/var/log/ytuner.log
ExecStartPre=/bin/sleep 15
Restart=always
ExecStop=/bin/date

[Install]
WantedBy=multi-user.target

**Comment by coffeegreg** [comment]
> Model: RX-V675 The YTuner service runs fine now. But there are still some issues
> 
> RX V675 IP: 192.168.178.2 Default gateway (first try): 192.168.178.1 (internet router ip) -> streams are working (fetch stations from YTuner is not working) Default gateway (second try) : 192.168.178.3 (YTuner) -> streams are not working (fetch stations from Ytuner is working) DNS1: 192.168.178.3 (YTuner) DNS2: 192.168.178.3 (YTuner)

The YTuner application itself does not provide a router(gateway) service. You have to use `192.168.178.1 (internet router ip)` as a gateway for your AVR device and of course as a gateway for YTuner machine as well.
Yes, your AVR's DNS settings are correct and should be IP address of your YTuner machine. `192.168.178.3` in this case.
Don't forget to set correct DNSs on YTuner machine like `8.8.8.8`, `9.9.9.9` or any others delivered/supported by your ISP.
Then, if you still have problems, enable `MessageInfoLevel=4` (debug mode), restart YTuner and copy the console log messages here. We'll try to analyze what happened with your YTuner application.

**Comment by coffeegreg** [comment]
In the meantime while I'm working on [this](https://github.com/coffeegreg/YTuner/issues/11#issuecomment-1857649550) I'm thinking about putting YTuner into a Docker container. 
Does this make any sense since my YTuner with TinyCore Linux fit on a 30MB very old flash drive? :thinking:

**Comment by seldam** [comment]
My service is running. Here is some debug:

1-1-24 14:40:24 : Inf : Loading RB UUIDs cache file.
1-1-24 14:40:24 : Inf : Successfully loaded 44155 RB UUIDs from cache file.
1-1-24 141-1-24 14:41:55 : Dbg : GET /setupapp/Yamaha/asp/BrowseXML/loginXML.asp?mac=EB004339AFF7B9BEEC8A0ABC939B316C&fver=W&dlang=eng&startitems=1&enditems=10.
1-1-24 14:41:55 : Dbg : GET /setupapp/Yamaha/asp/BrowseXML/loginXML.asp?mac=EB004339AFF7B9BEEC8A0ABC939B316C&fver=W&dlang=eng&startitems=1&enditems=10.
1-1-24 14:42:08 : Dbg : GET /setupapp/Yamaha/asp/BrowseXML/loginXML.asp?mac=EB004339AFF7B9BEEC8A0ABC939B316C&fver=W&dlang=eng&startitems=1&enditems=10.
1-1-24 14:42:08 : Dbg : GET /setupapp/Yamaha/asp/BrowseXML/loginXML.asp?mac=EB004339AFF7B9BEEC8A0ABC939B316C&fver=W&dlang=eng&startitems=1&enditems=10.
1-1-24 14:46:58 : Dbg : GET /setupapp/Yamaha/asp/BrowseXML/loginXML.asp?mac=EB004339AFF7B9BEEC8A0ABC939B316C&fver=W&dlang=eng&startitems=1&enditems=10.
1-1-24 14:46:58 : Dbg : GET /setupapp/Yamaha/asp/BrowseXML/loginXML.asp?mac=EB004339AFF7B9BEEC8A0ABC939B316C&fver=W&dlang=eng&startitems=1&enditems=10.
1-1-24 14:47:13 : Dbg : GET /setupapp/Yamaha/asp/BrowseXML/loginXML.asp?mac=EB004339AFF7B9BEEC8A0ABC939B316C&fver=W&dlang=eng&startitems=1&enditems=10.
1-1-24 14:47:13 : Dbg : GET /setupapp/Yamaha/asp/BrowseXML/loginXML.asp?mac=EB004339AFF7B9BEEC8A0ABC939B316C&fver=W&dlang=eng&startitems=1&enditems=10.
1-1-24 14:50:57 : Dbg : GET /setupapp/Yamaha/asp/BrowseXML/loginXML.asp?mac=EB004339AFF7B9BEEC8A0ABC939B316C&fver=W&dlang=eng&startitems=1&enditems=10.
1-1-24 14:50:57 : Dbg : GET /setupapp/Yamaha/asp/BrowseXML/loginXML.asp?mac=EB004339AFF7B9BEEC8A0ABC939B316C&fver=W&dlang=eng&startitems=1&enditems=10.

**Comment by coffeegreg** [comment]
Yes ... There is a bug :lady_beetle: in the code but don't worry. Fix is on the way and YTuner will work on your Yamaha soon. Hang on ...
Thanks for reporting your problems. :+1:  This allows me to fix and improve YTuner.

**Comment by coffeegreg** [comment]
Here we are ... Please try YTuner v1.1.2.

**Comment by TheBossME** [comment]
1.1.2 tested on Yamaha DSP-z7 with success.

**Comment by seldam** [comment]
1.1.2 tested on Yamaha RX-V675 with success.

**Comment by coffeegreg** [comment]
> 1.1.2 tested on Yamaha RX-V675 with success.

May I add your RX-V675 to `Confirmed working` list ? :notes:
