### ISSUE TITLE
"IPAddress" option does not work

### ISSUE THREAD

**Issue by citronalco** [coffeegreg/YTuner#2]
In ytuner.ini, I've set `IPAddress=127.0.0.1`, but ytuner binds to my machine's address 192.168.3.1:

```
$ ./ytuner
YTuner v1.0.0 Copyright (c) 2023 Greg P. (https://github.com/coffeegreg)
20-7-23 16:32:51 : Inf : Starting services...
20-7-23 16:32:51 : Inf : Getting Radio-browser.info UUIDs...
20-7-23 16:32:51 : Inf : Successfully loaded 10 my stations.
20-7-23 16:32:51 : Inf : Web server listening on: 192.168.1.1:9985.
20-7-23 16:32:56 : Inf : Successfully downloaded 39708 RB UUIDs.
```

**Comment by coffeegreg** [comment]
I probably know why you want the web server to start listening on the loopback IP address but I'm not sure if it's necessary.
Filtering the loopback IP address from the list of all IP addresses of other interfaces is implemented in one of the libraries used by YTuner. I can fix it and remove this filter to add the ability to support the web service and DNS service on the loopback address (127.0.0.1) and I have even prepared it, but ... then YTuner will reply an XML message to the AVR device in which it gives its IP address and the port on which the web service is listening. In our case, the loopback IP address (127.0.0.1) will of course prevent the AVR device from communicating with the YTuner web server.
To solve this problem, it would be necessary to add two new parameters with the IP addresses on which the web service and the DNS service should listen, and the existing IPAddress in the Configuration group in the ytuner.ini file would mean the unchanged IP address (+ additionally TCP port) that will be sent in XML messages to the AVR devices.
The AVR device will then send HTTP requests to this address and port, and these in turn will then be redirected to those on which YTuner is actually listening.
Is this the effect you would like to achieve?

**Comment by citronalco** [comment]
I already have a web server and a DNS server running. Because of this my plan was to do the required DNS configuration on my own and let YTuner only listen on localhost, on a port >1024 (to avoid to have to run it as root), and then configure a simple reverse proxy on the web server.
I did not know that port number and IP address are used in the XML replies.

As far as I understand, YTuner could simply always say "port 80" in its answers - that's the only port client devices try, or?
Filtering out localhost for the automatic IP address detection is fine. Being able to override the detected address with 127.0.0.1 would only make sense if there would be a also possibility to manually set the IP address being used in the XML replies.
Guess this is not a bug then, more a whish :)

**Comment by coffeegreg** [comment]
I will add new parameters that will allow you to do what you described.
I'll try to do it on some rainy day next week when I find a little bit of time.

**Comment by coffeegreg** [comment]
Please check the new version of YTuner (v1.0.1). Now it looks like this:
```
YTuner v1.0.1 Copyright (c) 2023 Greg P. (https://github.com/coffeegreg)
2023-07-26 16:24:33 : Inf : Starting services...
2023-07-26 16:24:33 : Inf : Loading RB UUIDs cache file.
2023-07-26 16:24:33 : Inf : Successfully loaded 40112 RB UUIDs from cache file.
2023-07-26 16:24:33 : Inf : Successfully loaded 10 my stations.
2023-07-26 16:24:33 : Inf : DNS server listening on: 192.168.1.2:53.
2023-07-26 16:24:33 : Inf : Web server listening on: 127.0.0.1:8080.
2023-07-26 16:24:33 : Inf : AVRs HTTP requests IP target: 192.168.1.2.
```

Now, you should be able to do what you wrote about earlier. Please let me know if it works properly for you.
Please share information about:
- What is the OS and CPU arch of your YTuner machine?
- What AVR devices does your Tuner work with? Let me update the list of YTuner supported devices.
