### ISSUE TITLE
Issues with version 1.2.0 on DSP-Z7

### ISSUE THREAD

**Issue by TheBossME** [coffeegreg/YTuner#22]
Hi Greg,

I'll take a short look into the Linux x64 version.

First: The 1.1.2 version works actually at his best.

With 1.2.0 version, new/old issues found, like the "spaces" issue.
- avr.ini filter does not work as aspected.
  question: how to filter best the misconfigured genres from the database ?
- ID tags filter removed ?.
- country filter not working properly 
  "Arab Emirates" is,empty now (where i put lots of stations.
  aigainst the "spaces issue", do,you remember ?

- AVR specific bookmarks file wasn't read ?. Only the bookmarks.xml was read. equal if CommonAVR is set to 1 or 0.
  Maybe special with my AVR (don't know)

Download the whole database from the web api is a good step forward. 

I switched back to 1.1.2 and bookmarks are also not there (don't know the reason actually.)

Please check the "BLANK" issue we,do,have again with "the Arab Emirates" on your AVR and let me know if you got content.

The "BLANK" issue do exist also on genre,countries, and so on.

If you're thinking about replacing stations.yaml file with other solutions, my idea here is to do it with SQLite database too. Using same structure than in rb.db file, or using a marking database pointing to the rb.db. Hope you do understand what I mean. 

Thanks 🙏

**Comment by coffeegreg** [comment]
Hi Beatrice
>    avr.ini filter does not work as aspected.

Please, give me an example of your `avr.ini` setting with expected filtering and real results. Are you sure you're using common `avr.ini` with `CommonAVRini=1`?

> ID tags filter removed ?.

:confused: What kind of "ID tags filter" ? Please give me an example.

>country filter not working properly
> "Arab Emirates" is,empty now (where i put lots of stations.

:confused: What do you mean? Where did you "put lots of stations"? Radio-browser.cache (old one based on `.cache` files and new one based on sqlite database) should not be edited manually by users. :confused: 

>bookmarks file wasn't read ?.

I didn't change anything with bookmarks with this or even previous release. For me they still work as before ... I checked it as usual when testing the new release. Pay attention on `CommonBookmark` setting of `ytuner.ini`. `CommonBookmark=1` mean one common bookmark file `bookmark.xml` for all AVRs (if own more that one like me). `CommonBookmark=0` mean every AVR has it's own bookmark xml file. 

> Please check the Arab Emirates on your AVR and let me know if you got content. 

Sure, but what kind of filter/order settings (`avr.ini` - `CommonAVRini=1`?) do you use?

**Comment by TheBossME** [comment]
- CommonAVRini=1 is set.
  The AVR uses the bookmarks.xml I've copied the existing specific xxxxxx.xml file to bookmarks.xml (book,arks globally back. Imhave only one AVR, so no direct issue for me.

- spaces issue is back !!. Check categories, countries and with a space. you copied old not fixed code  😂 haha. (maybe)

I,do have modified my prior message. Please reread.

Thanks.

**Comment by coffeegreg** [comment]
> spaces issue is back !!. Check categories, countries and with a space. you copied old not fixed code 😂 haha. (maybe)

Not really. Old cache types like `catFile` works as expected (based on already fixed code) and there is no "space" issue. :wink: 
But.. Yes, indeed the new one database cache like `catDB` has this issue. :wink: Point for you. :+1: Easy to fix with additional 10 characters function :smile: Already did.
I understand that this "space" issue is the same as the "BLANK" issue.

> AVR specific bookmarks file wasn't read ?. Only the bookmarks.xml was read. equal if CommonAVR is set to 1 or 0.

I've just checked. With `CommonAVR=1` my AVRs read `avr.ini` settings and with `CommonAVR=0` indepandent xxxxxx.xml files that are associated with the `mac` AVR parameter.

> I switched back to 1.1.2 and bookmarks are also not there (don't know the reason actually.)

Check your `CommonBookmark` setting. It works similarly to `CommonAVR` described above, except that bookmarks are saved in xml files
Should I check/fix anything else before I'll release YTuner v1.2.1 ? :thinking:

**Comment by TheBossME** [comment]
I,do have Bookmarkcommon on 1

So both parameters set to 1 not 0

**Comment by coffeegreg** [comment]
I have RPI 1 and RPI 4/4GB. This Proxmox panel looks quite nice but I don't have time to play with it right now.
Yes, my old thin client running YTuner is very slow and needs about 10 W of power (I can also use the on/off button :wink: ), but think if I create software that can run quickly and effectively on such a platform, what performance will it have on a modern platforms. :rocket: 
The problem nowadays is that software developers don't care about every CPU cycle (and usually have no idea what that is and how it works) and when you ask about performance the answer is always the need to increase CPU power and memory space or by scaling horizontally and adding new machines or POD and containers. And business departments have to pay for it and the result is some mega hardware platforms that don't do much, but are fashionable, modern and impress others. :laughing:

**Comment by coffeegreg** [comment]
> I do have Free Pascal Compiler installed onto an alpine 3.19 VM on my raspberry PI to compile your project on arm64 directly.
>
>What's needed additionally to the /usr/local installed FPC ?

I use FPC based on Windows platform and cross-compile YTuner for other platforms too. You definitely need the Trunk verion of FPC (v3.31) and the last `Indy Library` to compile the project (Look at `Dependencies` on [README.md](https://github.com/coffeegreg/YTuner/blob/master/README.md)) If you want to build your own YTuner binaries, you'll need to read/learn a bit about FPC, but it's worth doing. Due to the fact that FPC compiles to native code and does not need any interpreters or frameworks, it is second only to C/C++ in terms of speed, but it is very simple, really fast and constantly developed by FPC team.
I'm sorry but I don't have time to focus on your VM and FPC. You will find tutorials online that will help you with this and you will be more satisfied when your binaries are built. :+1: 

Now I'll prepare fixed YTuner v1.2.1 binaries and in the coming weeks I will devote time to the most important person in the world, my son, in preparation for the math competition. :crossed_fingers: Yes, and also I'm still looking for a new interesting job... :+1:

**Comment by TheBossME** [comment]
My (ex) company do have locations in Polant too.

If you found time to go into deeper contact and you're willing to to send me your CV.I will check what I can do for you to be membership of the best company I ever worked for 🥂😂🤣

**Comment by coffeegreg** [comment]
> For FPC. The libraries do not exist actually for alpine Linux...

Libraries = source code of libraries used to compile whole YTuner. OS does not matter here.
An application built using FPC is a native application, not like a python/java/.NET C# "thing", and does not need anything else to run except optional dynamic libraries such as OpenSSL or SQLite.
Indy libraries fork = https://github.com/coffeegreg/Indy.
I suggest to build AMD64 Linux 64 VM and use FPC on it.

**Comment by coffeegreg** [comment]
Here we are. New release v1.2.1 is ready. :rocket:
