### ISSUE TITLE
installation question

### ISSUE THREAD

**Issue by phlnil** [coffeegreg/YTuner#31]
Hi, 
I am missing something :
in Alpine 3.19.1
downloaded and unzipped : [1.2.2 linux ](https://github.com/coffeegreg/YTuner/releases/download/1.2.2/ytuner-1.2.2-x86_64-linux.zip)

and even set chmod +x ytuner
```
# ytuner
-ash: ytuner: not found
```

 # ls 
 cache       config      ytuner      ytuner.ini [<--- ytuner is there!]
how to solve ?
Thank you !

**Comment by TheBossME** [comment]
You need to check the installed libraries for ytuner functionality under alpine Linux. Please check documentation.

**Comment by phlnil** [comment]
Hi Beatrice, thank you for your reply!
I tried arch (but anyway I will check it again) and even to follow steps for docker (Initially I thought to follow [those](https://github.com/coffeegreg/YTuner/blob/master/README.md#build)),
but even if I know some efforts are (or will be ) needed (pihole or nginx) I  tried at last to try to run the ytuner executable, 
No luck :) 
I could create a lxc for ytuner... and I had chosen alpine, maybe is another one a better platform ?(debian)

**Comment by TheBossME** [comment]
I'm using Debian 12 with no issues in an LXC in Proxmox.

**Comment by coffeegreg** [comment]
Hi @phlnil
Maybe the answer to your question is very simple... :smiley: 
If you are in the directory where the `ytuner` binary file and the `ytuner.ini` configuration file are unzipped, you should run ytuner with the command:
```
# ./ytuner
```
or if you are not a root :
```
$ sudo ./ytuner
```
Remember that Alpine Linux is quite specific and you need a `libc6-compat` library to execute any binaries generated by pascal or c compilers. Here it is : https://pkgs.alpinelinux.org/packages?name=libc6-compat&branch=v3.18
Optionally you'll need `sqlite-libs` too to support [catDB,catMemDB,catPermMemDB] cache types.
Here it is : https://pkgs.alpinelinux.org/packages?name=sqlite-libs&branch=v3.18
Select the file version appropriate for your CPU architecture.

**Comment by coffeegreg** [comment]
@TheBossME 
>There should be discussions between Greg an me. The result is to build very small docker images with alpine Linux etc.

My dear Beatrice. :heart: 
If you can add or improve anything what I have described here : https://github.com/coffeegreg/YTuner/blob/master/doc/DOCKER.md or if you want to prepare docs about run YTuner with LXC in Proxmox ... feel free! :rocket:  It will be my pleasure and honor to add your documentation to the YTuner project. :+1:

**Comment by coffeegreg** [comment]
@phlnil 
> `alpine:~/ytuner-1.2.3-aarch64-linux# ./ytuner

>./ytuner: line 0: syntax error: unexpected "&"`

Strange ... :thinking: Unfortunately I don't have any Alpine Linux virtual machine to check it. :disappointed: 
Please try with Alpie Linux v3.18 with all mentioned libraries and let us know.

**Comment by TheBossME** [comment]
> Thank you for  your reply!
> 
> I had tried also with 
> 
> `alpine:~/ytuner-1.2.3-aarch64-linux# ./ytuner  
> 
> 
> 
> ./ytuner: line 0: syntax error: unexpected "&"`
> 
> so I will get the v3.18 and check that ! 
> 
> in the meanwhile thank you again.
> 
> 

That's why the additional system libraries are not installed. 
If you haven't knowledge about alpine, please use Debian 12 with the proper architecture version.

**Comment by TheBossME** [comment]
> @TheBossME 
> 
> >There should be discussions between Greg an me. The result is to build very small docker images with alpine Linux etc.
> 
> 
> 
> My dear Beatrice. :heart: 
> 
> If you can add or improve anything what I have described here : https://github.com/coffeegreg/YTuner/blob/master/doc/DOCKER.md or if you want to prepare docs about run YTuner with LXC in Proxmox ... feel free! :rocket:  It will be my pleasure and honor to add your documentation to the YTuner project. :+1: 

There are lots of descriptions to install LXC containers in Proxmox. That's so,easy. And in the LXC it works like Hardware based or VM based installations.

**Comment by phlnil** [comment]
![err](https://github.com/user-attachments/assets/e7c6d630-c3c4-4222-a9a6-80c40b142dac) 
I will wait :)

**Comment by phlnil** [comment]
> > @TheBossME

> >  if you want to prepare docs about run YTuner with LXC in Proxmox ... feel free! 🚀  It will be my pleasure and honor to add your documentation to the YTuner project. 👍
> 
this will be awesome! 👍👍

**Comment by phlnil** [comment]
in alpine :`apk libc6-compat `
and thank you I finally see  : 
`   Inf : Starting services...`

**Comment by TheBossME** [comment]
> @TheBossME 
> 
> >There should be discussions between Greg an me. The result is to build very small docker images with alpine Linux etc.
> 
> 
> 
> My dear Beatrice. :heart: 
> 
> If you can add or improve anything what I have described here : https://github.com/coffeegreg/YTuner/blob/master/doc/DOCKER.md or if you want to prepare docs about run YTuner with LXC in Proxmox ... feel free! :rocket:  It will be my pleasure and honor to add your documentation to the YTuner project. :+1: 


for Alpine Linux I do the following:

- installing Alpine Linux 3.20 (upgrade from 3.18 works too)
- installing gcompat (compatibility Library
  command: apk add gcompat
- downloading the aarch64 binary package for ytuner
- unzip <ytuner aarch64 package> 
- change the executable bit after jumping to extraction dir
  command: chmod +x ytuner 
- start the Program
  ./ytuner

That's it.

**Comment by phlnil** [comment]
Thank you I will try !,

**Comment by TheBossME** [comment]
> Thank you I will try !, 
> 
> 

Do you have good knowledge with alpine Linux and service file creation ?. If yes, maybe you can help to create a proper service file for alpine Linux.
Thanks 🙏 
Beatrice

**Comment by phlnil** [comment]
Sorry, Beatrice, I don't know enough about it. 
Anyway even without db, ytuner works like a charm (with a pihole for dns), and with some  new lines on stations.ini.
I would try to use  the db and maybe dockerize it, but for now I am really happy... with this great sw. 
Thank you again!

**Comment by TheBossME** [comment]
Thanks are due to Greg, because he did the work to create something new and much better performing piece of software from an existing python project.

I have now managed to get all the components running inside an LXC container with alpine Linux 3.20 with all functions. Including the autostart of the ytuner service after a reboot of the Proxmox hypervisor. I can't understand why Greg still doesn't use a Proxmox hypervisor. Even my small raspberry pi's run with Proxmox 8.2.x (unofficial arm64 version) 
Proxmox needs some memory, but even on the Raspi 4 with 4 GB RAM I have some LXC and also VM's running Ubuntu. 

My centralized Datacenter is running since mid 2021 on Minisforum HM80 Minicomputer without issues 24/7.
And again: Life without Proxmox is possible, but pointless ![image](https://github.com/user-attachments/assets/807d8abe-7a88-4c35-a7fe-fb8b36e2f5ec)

**Comment by coffeegreg** [comment]
> ... Anyway even without db, ytuner works like a charm (with a pihole for dns), and with some new lines on stations.ini. I would try to use the db and maybe dockerize it, but for now I am really happy... with this great sw. Thank you again!

@phlnil 
I'm curious why you decided to use pihole for dns instead of using the built-in YTuner DNS service... :thinking:
Anyway, enjoy the sound with YTuner and your...  AVR... but wait a minute... You didn't mention what AVR equipment you own that works with YTuner. :wink: Maybe I should add the new AVR type into "Confirmed working" list. :rocket:

**Comment by coffeegreg** [comment]
@TheBossME 
I like your passion for proxmox. :+1:  I have similar with coding but not necessarily with virtualization tools.
> I can't understand why Greg still doesn't use a Proxmox hypervisor.

If I have free time, I'd rather spend it on coding with Freepascal or teaching my son C/C++ coding... but proxmox is still on my "to-do" list. :wink: Yep ... this list is very long :wink: 
My RPI 4/4GB is sitting in a drawer, waiting for its time to come. :eyes:

**Comment by phlnil** [comment]
> > ... Anyway even without db, ytuner works like a charm (with a pihole for dns), and with some new lines on stations.ini. I would try to use the db and maybe dockerize it, but for now I am really happy... with this great sw. Thank you again!
> 
> @phlnil I'm curious why you decided to use pihole for dns instead of using the built-in YTuner DNS service... 🤔 Anyway, enjoy the sound with YTuner and your... AVR... but wait a minute... You didn't mention what AVR equipment you own that works with YTuner. 😉 Maybe I should add the new AVR type into "Confirmed working" list. 🚀
😪Nope, mine is already on the List... (and was a reason to try your SW ! 😁) I would test Ytuner with the db... just to try to work with the original and so old denon app (for now : old presets(<=50) in the app (and saved I think also in the denon) cannot be used). More important I will need to find a way to change the preset with Homeassistant, that was indeed possible before and useful to me).
