### ISSUE TITLE
unknown route - denon avr 2313

### ISSUE THREAD

**Issue by Stijn-Daniels** [coffeegreg/YTuner#33]
Hi Greg!

I'm trying to get Ytuner to work with my denon avr2313. When i change the DNS and select 'internet radio' on the denon it opens the playing screen with the message "track not found" 
I cannot get to the navigation menu for internet radio. 

The logging

```
5-10-24 12:31:28 : Inf : Starting services...
5-10-24 12:31:28 : Inf : Successfully loaded 3 my stations.
5-10-24 12:31:28 : Dbg : Database library : 3.37.2.
5-10-24 12:31:28 : Inf : Checking local database.
5-10-24 12:31:28 : Inf : Local database is ready.
5-10-24 12:31:28 : Inf : DNS Service: listening on: 192.168.1.112:53.
5-10-24 12:31:28 : Inf : Web Service: listening on: 192.168.1.112:80.
5-10-24 12:32:27 : Dbg : GET /setupapp/denon/asp/browsexm2/loginXML.asp?mac=F4A68170A1EDB49A20C42B87462AC99A&fver=1.754333&dlang=dut&startitems=1&enditems=10.
5-10-24 12:32:28 : Dbg : Unknown route : GET /setupapp/denon/asp/func/dynamOD.asp?ex45v=0005CD2B126E&id=592.
```

I tried both with a direct install as well as with docker, but the results are the same. I don't know if there are settings i should be trying. If you have an idea, please let me know!

**Comment by Larsvb0** [comment]
how does your stations.ini look like? 

try this:
[NPO]
  NPO Radio 2=https://icecast.omroep.nl/radio2-bb-mp3|https://radioned.nl/radio2.png
  NPO 3FM=https://icecast.omroep.nl/3fm-bb-mp3|https://radioned.nl/3fm.png
  NPO Radio 5=https://icecast.omroep.nl/radio5-bb-mp3|https://radioned.nl/radio5.png
  NPO Soul and Jazz=http://icecast.omroep.nl/radio6-bb-mp3|https://radioned.nl/nposouljazz.png

**Comment by Stijn-Daniels** [comment]
using your ini, so the ini looks like this:
```
cat config/stations.ini
[NPO]
NPO Radio 2=https://icecast.omroep.nl/radio2-bb-mp3|https://radioned.nl/radio2.png
NPO 3FM=https://icecast.omroep.nl/3fm-bb-mp3|https://radioned.nl/3fm.png
NPO Radio 5=https://icecast.omroep.nl/radio5-bb-mp3|https://radioned.nl/radio5.png
NPO Soul and Jazz=http://icecast.omroep.nl/radio6-bb-mp3|https://radioned.nl/nposouljazz.png
```


```
6-10-24 07:47:02 : Inf : Starting services...
6-10-24 07:47:02 : Inf : Successfully loaded 4 my stations.
6-10-24 07:47:02 : Dbg : Database library : 3.37.2.
6-10-24 07:47:02 : Inf : Checking local database.
6-10-24 07:47:02 : Inf : Local database is ready.
6-10-24 07:47:02 : Inf : DNS Service: listening on: 192.168.1.112:53.
6-10-24 07:47:02 : Inf : Web Service: listening on: 192.168.1.112:80.
6-10-24 07:47:07 : Dbg : GET /setupapp/denon/asp/BrowseXML/loginXML.asp?token=0.
6-10-24 07:47:07 : Dbg : GET /setupapp/denon/asp/browsexm2/loginXML.asp?mac=F4A68170A1EDB49A20C42B87462AC99A&fver=1.754333&dlang=dut&startitems=1&enditems=10.
6-10-24 07:47:08 : Dbg : Unknown route : GET /setupapp/denon/asp/func/dynamOD.asp?ex45v=0005CD2B126E&id=592
```

So it seems the ini gets loaded, but i get the same problem.

**Comment by coffeegreg** [comment]
Hi @Stijn-Daniels
It looks like your Denon AVR-2313 generates slightly different queries than other AVRs we know of.
Correct recognition and handling of different types of queries generated by different types of AVR devices is the result of the work of our entire community of people who like YTuner. As you probably realize, I cannot own all the types of AVR equipment at home to support them via YTuner. This would be a very expensive hobby for me. :wink: 
Of course I can add support for new types of queries that your Denon AVR-2313 is familiar but I will need your active help. 
I will only need from you a precise description of what you select on your AVR screen and what entries YTuner generates in its log releated to your specific action in AVR.
Are you ready to help? :question: 
Are you ready to join our YTuner community : https://github.com/coffeegreg/YTuner/stargazers ? :star: 
Are you ready to enjoy free internet radio stations on your device? :notes: :radio: 
Are you ready for this? :rocket:  Are you ... ? :smiley:

**Comment by Stijn-Daniels** [comment]
Sign me up!
And yeah i had the feeling this had to do with me having an older AVR. But if we can get it to work... awesome!

On the AVR i select 'internet radio'. the moment i select it, i get these log entries:
```
6-10-24 07:47:07 : Dbg : GET /setupapp/denon/asp/BrowseXML/loginXML.asp?token=0.
6-10-24 07:47:07 : Dbg : GET /setupapp/denon/asp/browsexm2/loginXML.asp?mac=F4A68170A1EDB49A20C42B87462AC99A&fver=1.754333&dlang=dut&startitems=1&enditems=10.
6-10-24 07:47:08 : Dbg : Unknown route : GET /setupapp/denon/asp/func/dynamOD.asp?ex45v=0005CD2B126E&id=592
```

To me it feels like it tries to start the previously playing station and cannot find it anymore? 

Let me know what other info you can use!

**Comment by TheBossME** [comment]
As a radio listener, I am often ridiculed by the script kiddies of this world. They really only know Spotify and Netflix etc. These people have never actually heard of radio and television. I'm old because I'm the radio & TV generation. No, on the contrary, I'm just as happy about new technology and enjoy having my sound list presented to me by other people. For me, it's like when I used to go to the disco and play at the local radio station. I helped shape the program there.

happy radio

And Greg, I'm very amused by your comments 👍🤣🫶👍🙏
Sorry for me, that we never met in real life. Could have much fun 🙋‍♀️. 

And, I'm here to assist and support anybody with the same love ❤️ to music and technic and Software and hardware. 

Happy listening 👂 📻

**Comment by TheBossME** [comment]
One question, from my end, have you set debug to level 4 in the application.ini file ?

**Comment by coffeegreg** [comment]
> To me it feels like it tries to start the previously playing station and cannot find it anymore?

Exactly! :+1: 
First of all we need to get rid of this annoying request to start the previously playing station. After that we will try to analyze all your avr requests and prepare an appropriate response for it. I'm not saying it will be easy but I think it's worth a try because your Denon AVR-2313 looks beautiful and I bet its sound is also incredibly clean. :sound: :notes: 
Please note that you will have to forget about the same menu for "Internet Radio" that you have known so far :
![obraz](https://github.com/user-attachments/assets/e3b70561-0859-4f78-abdf-9f7bbcad714a)

YTuner creates its own menu which you can also customize to some extent. For more information, see [README.MD](https://github.com/coffeegreg/YTuner/blob/master/README.md) or read some opened/closed [issues](https://github.com/coffeegreg/YTuner/issues) or [discussions](https://github.com/coffeegreg/YTuner/issues).
Now, let me know about your YTuner machine platform : OS and CPU arch.
In the next steps I will try to prepare YTuner binaries for this platform for you until our tests are finished. Then there will be an official release of the new version with support for your avr ... of course if we can solve the mystery of its correct support. :thinking:

**Comment by Stijn-Daniels** [comment]
> One question, from my end, have you set debug to level 4 in the application.ini file ?

yes

**Comment by coffeegreg** [comment]
> One question, from my end, have you set debug to level 4 in the application.ini file ?

Yes, he does :
6-10-24 07:47:08 : **Dbg** : Unknown route : GET /setupapp/denon/asp/func/dynamOD.asp?ex45v=0005CD2B126E&id=592

**Comment by Stijn-Daniels** [comment]
I run ytuner on linux 64 ( ytuner-1.2.3-x86_64-linux.zip ). Currently its running on ubuntu 22.04. I can also run it on Docker or spin up a different OS if needed.

**Comment by coffeegreg** [comment]
>As a radio listener, I am often ridiculed by the script kiddies of this world.

Yeah, me too... :wink: 
>They really only know Spotify and Netflix etc. These people have never actually heard of radio and television. I'm old because I'm the radio & TV generation.

I feel the same way... but I haven't watched TV in a long time. Too many commercials... :wink: 

>And Greg, I'm very amused by your comments 👍🤣🫶👍🙏
Sorry for me, that we never met in real life. Could have much fun 🙋‍♀️.

Yeah... that could be interesting, fun... and again not so impossible :wink: :smile: 

>And, I'm here to assist and support anybody with the same love ❤️ to music and technic and Software and hardware.

I confirm, :+1:  Beatrice is the most active and helpful member of our community. Without her, many features in YTuner would not exist. :rocket:

**Comment by TheBossME** [comment]
Then we now have the concentrated human intelligence at our disposal to solve any problem. 🙏🤣👍🫶

**Comment by coffeegreg** [comment]
Ok. lets back to work :wink: 
@Stijn-Daniels 
After that :
>6-10-24 07:47:07 : Dbg : GET /setupapp/denon/asp/BrowseXML/loginXML.asp?token=0.
6-10-24 07:47:07 : Dbg : GET /setupapp/denon/asp/browsexm2/loginXML.asp?mac=F4A68170A1EDB49A20C42B87462AC99A&fver=1.754333&dlang=dut&startitems=1&enditems=10.
6-10-24 07:47:08 : Dbg : Unknown route : GET /setupapp/denon/asp/func/dynamOD.asp?ex45v=0005CD2B126E&id=592

Have you tried to pressing `stop` or :thinking:  `back` or :thinking: any other button like `menu` ? :thinking: 
any addional lines in YTuner's log ? Any other "GET" request(s) ?

**Comment by Stijn-Daniels** [comment]
While in the 'now playing' screen there is a large banner saying "track niet gevonden" (track not found).
i have to wait ~10 seconds before any new commands are registered.

back -> no entry -> goes to the 'network menu'
stop -> no entry -> goes to the 'network menu'
menu -> no entry -> nothing happens

Haven't found a button that has any effect. I also tried resetting the network settings in the hope that it would forget this 'previous station'

**Comment by coffeegreg** [comment]
OK. First af all ... are you sure there is a connection between AVR and YTuner? Any firewalls?
In this GET query :
> 6-10-24 07:47:07 : Dbg : GET /setupapp/denon/asp/browsexm2/loginXML.asp?mac=F4A68170A1EDB49A20C42B87462AC99A&fver=1.754333&dlang=dut&startitems=1&enditems=10.

AVR should receive the answer like that :
```
<ListOfItems>
<ItemCount>4</ItemCount>
<Item>
<ItemType>Dir</ItemType>
<Title>*** YTuner ***</Title>
<UrlDir>http://192.168.1.30/ytuner/about?ytuner=true</UrlDir>
<UrlDirBackUp>http://192.168.1.30/ytuner/about?ytuner=true</UrlDirBackUp>
<DirCount>2</DirCount>
</Item>
<Item>
<ItemType>Dir</ItemType>
<Title>Favourites</Title>
<UrlDir>http://192.168.1.30/ytuner/bookmark?ytuner=true</UrlDir>
<UrlDirBackUp>http://192.168.1.30/ytuner/bookmark?ytuner=true</UrlDirBackUp>
<DirCount>0</DirCount>
</Item>
<Item>
<ItemType>Dir</ItemType>
<Title>My Stations</Title>
<UrlDir>http://192.168.1.30/ytuner/mystations?ytuner=true</UrlDir>
<UrlDirBackUp>http://192.168.1.30/ytuner/mystations?ytuner=true</UrlDirBackUp>
<DirCount>9</DirCount>
</Item>
<Item>
<ItemType>Dir</ItemType>
<Title>Radio Browser</Title>
<UrlDir>
http://192.168.1.30/ytuner/radiobrowser?ytuner=true
</UrlDir>
<UrlDirBackUp>
http://192.168.1.30/ytuner/radiobrowser?ytuner=true
</UrlDirBackUp>
<DirCount>4</DirCount>
</Item>
</ListOfItems>
```
This answer is suitable for YTuner v1.2.4 alpha but it doesn't matter at all.
Can you use a web browser (**on other machine than YTuner**) and query YTuner like this one :
`http://[your-ytuner-machine-ipv4-address-or-domain-name]/setupapp/Yamaha/asp/BrowseXML/loginXML.asp?mac=xxxxxxxxxxxxxx&dlang=eng&fver=W&start=1&howmany=8`

??

**Comment by Stijn-Daniels** [comment]
I get this in logging:
```
6-10-24 10:21:19 : Dbg : GET /setupapp/Yamaha/asp/BrowseXML/loginXML.asp?mac=xxxxxxxxxxxxxx&dlang=eng&fver=W&start=1&howmany=8.
```

My browser shows this:

```
<ListOfItems>
<ItemCount>3</ItemCount>
<Item>
<ItemType>Dir</ItemType>
<Title>My stations</Title>
<UrlDir>
http://192.168.1.112/ytuner/my_stations?ytuner=true
</UrlDir>
<UrlDirBackUp>
http://192.168.1.112/ytuner/my_stations?ytuner=true
</UrlDirBackUp>
<DirCount>1</DirCount>
</Item>
<Item>
<ItemType>Dir</ItemType>
<Title>Radio browser</Title>
<UrlDir>
http://192.168.1.112/ytuner/radiobrowser?ytuner=true
</UrlDir>
<UrlDirBackUp>
http://192.168.1.112/ytuner/radiobrowser?ytuner=true
</UrlDirBackUp>
<DirCount>4</DirCount>
</Item>
<Item>
<ItemType>Dir</ItemType>
<Title>Bookmark</Title>
<UrlDir>http://192.168.1.112/ytuner/bookmark?ytuner=true</UrlDir>
<UrlDirBackUp>http://192.168.1.112/ytuner/bookmark?ytuner=true</UrlDirBackUp>
<DirCount>1</DirCount>
</Item>
</ListOfItems>
````

**Comment by coffeegreg** [comment]
What about this one :
`http://[your-ytuner-machine-ipv4-address-or-domain-name]/setupapp/denon/asp/browsexm2/loginXML.asp?mac=F4A68170A1EDB49A20C42B87462AC99A&fver=1.754333&dlang=dut&startitems=1&enditems=10`
?

**Comment by Stijn-Daniels** [comment]
```
6-10-24 10:32:29 : Dbg : GET /setupapp/denon/asp/browsexm2/loginXML.asp?mac=F4A68170A1EDB49A20C42B87462AC99A&fver=1.754333&dlang=dut&startitems=1&enditems=10.
```

```
<ListOfItems>
<ItemCount>3</ItemCount>
<Item>
<ItemType>Dir</ItemType>
<Title>My stations</Title>
<UrlDir>
http://192.168.1.112/ytuner/my_stations?ytuner=true
</UrlDir>
<UrlDirBackUp>
http://192.168.1.112/ytuner/my_stations?ytuner=true
</UrlDirBackUp>
<DirCount>1</DirCount>
</Item>
<Item>
<ItemType>Dir</ItemType>
<Title>Radio browser</Title>
<UrlDir>
http://192.168.1.112/ytuner/radiobrowser?ytuner=true
</UrlDir>
<UrlDirBackUp>
http://192.168.1.112/ytuner/radiobrowser?ytuner=true
</UrlDirBackUp>
<DirCount>4</DirCount>
</Item>
<Item>
<ItemType>Dir</ItemType>
<Title>Bookmark</Title>
<UrlDir>http://192.168.1.112/ytuner/bookmark?ytuner=true</UrlDir>
<UrlDirBackUp>http://192.168.1.112/ytuner/bookmark?ytuner=true</UrlDirBackUp>
<DirCount>1</DirCount>
</Item>
</ListOfItems>
```

**Comment by coffeegreg** [comment]
Yup, it looks like YTuner answer correct, but this "correct" reply is not valid for your Denon.
AVR-2313 expects another. The question is: what kind? :thinking: 
Of course, this is not documented anywhere. All we have left is trial and error... I need to think and prepare something for the tests. :thinking:

**Comment by Stijn-Daniels** [comment]
Take your time and let me know what i can do to help!

**Comment by coffeegreg** [comment]
Let's strip returned xml...
Try this test release:
[ytuner-1.2.4+1-x86_64-linux.zip](https://github.com/user-attachments/files/17269135/ytuner-1.2.4%2B1-x86_64-linux.zip)

**Comment by Stijn-Daniels** [comment]
```
6-10-24 11:50:24 : Dbg : GET /setupapp/denon/asp/browsexm2/loginXML.asp?mac=F4A68170A1EDB49A20C42B87462AC99A&fver=1.754333&dlang=dut&startitems=1&enditems=10.
6-10-24 11:50:24 : Dbg : GET /setupapp/denon/asp/browsexm2/loginXML.asp?mac=F4A68170A1EDB49A20C42B87462AC99A&fver=1.754333&dlang=dut&startitems=1&enditems=10.
6-10-24 11:50:26 : Dbg : Unknown route : GET /setupapp/denon/asp/func/dynamOD.asp?ex45v=0005CD2B126E&id=592.
```

I briefly saw a different menu before the 'now playing' was opened. The top of the Menu was **Ytuner**. But again, i'm unable to navigate to that menu, and am stuck in the 'now playing'.

**Comment by coffeegreg** [comment]
> I briefly saw a different menu before the 'now playing' was opened. The top of the Menu was Ytuner. But again, i'm unable to navigate to that menu, and am stuck in the 'now playing'.

There is little progress ... Have you seen this menu with `*** YTuner ***` at the top before or just in the new version? :thinking: 
Try to press `stop` too.

**Comment by coffeegreg** [comment]
There is little progress ... 
Have you seen main menu with `My stations` at the top before (with YTuner v1.2.3)?

**Comment by Stijn-Daniels** [comment]
No not before. First time seeing that.
Buttons are still doing the same as before.

A different question, i noticed during startup of ytuner i get this message:
```
6-10-24 11:58:03 : Wrn : You are running out of INI file or your ytuner.ini file is outdated! Some features may not work properly! Check https://github.com/coffeegreg/YTuner/tree/master/cfg for the correct INI file for your version of YTuner.
```

The content of my stations.ini is pasted [here](https://github.com/coffeegreg/YTuner/issues/33#issuecomment-2395336234)
Can i ignore this warning for now?

**Comment by coffeegreg** [comment]
> Can i ignore this warning for now?
Please ignore this for now.
Have you seen main menu with `My stations` at the top before (with YTuner v1.2.3)?

**Comment by Stijn-Daniels** [comment]
Yup, i just used 1.2.3 and it shows My stations.

**Comment by coffeegreg** [comment]
> Yup, i just used 1.2.3 and it shows My stations.

Just for a moment you saw `My staions` and after that you stuck in the 'now playing' again?

**Comment by Stijn-Daniels** [comment]
YesOp 6 okt 2024 om 14:11 heeft Greg ***@***.***> het volgende geschreven:﻿

Yup, i just used 1.2.3 and it shows My stations.

Just for a moment you saw My Stations and after that you stuck in the 'now playing' again?

**Comment by coffeegreg** [comment]
Your Denon is a very stubborn beast :wink: It's hard to believe that it's impossible to interrupt the playback of a station that... no longer exists. 
OK. Let's try to "cure" your AVR and cheat it. It's time for some magic ... :magic_wand:  Try this one:
[ytuner-1.2.4+2-x86_64-linux.zip](https://github.com/user-attachments/files/17269427/ytuner-1.2.4%2B2-x86_64-linux.zip)

**Comment by coffeegreg** [comment]
>And yeah i had the feeling this had to do with me having an older AVR. But if we can get it to work... awesome!

BTW ... "older" doesn't mean "worst". When I see the "quality" of "new" model products and what they are made of, I definitely prefer the older ones. This applies to everything that is currently being manufactured, not just AVR. :confused:

**Comment by coffeegreg** [comment]
Is it possible that you have listened to SKYRADIO before? :thinking: 
I did a little research and it turned out that vtuner does not throw any HTTP codes in response :
![obraz](https://github.com/user-attachments/assets/ecb0a7b4-19fc-490d-b74b-84d3e139d299)
Very strange behavior. Maybe that's why your denon reacts so strangely because the lack of HTTP code is a vet rare occurrence. :open_mouth:

**Comment by Stijn-Daniels** [comment]
That could be the last station played yes.

**Comment by Stijn-Daniels** [comment]
> BTW ... "older" doesn't mean "worst". When I see the "quality" of "new" model products and what they are made of, I definitely prefer the older ones. This applies to everything that is currently being manufactured, not just AVR. 😕

It works with home assistant, spotify and works with most codecs. So for me its still ideal (and everything local!)

**Comment by Stijn-Daniels** [comment]
Hah nice debug surprise :-) 

```
6-10-24 15:04:25 : Dbg : GET /setupapp/denon/asp/BrowseXML/loginXML.asp?token=0.
6-10-24 15:04:25 : Dbg : GET /setupapp/denon/asp/browsexm2/loginXML.asp?mac=F4A68170A1EDB49A20C42B87462AC99A&fver=1.754333&dlang=dut&startitems=1&enditems=10.
6-10-24 15:04:25 : Dbg : GET /setupapp/denon/asp/browsexm2/loginXML.asp?mac=F4A68170A1EDB49A20C42B87462AC99A&fver=1.754333&dlang=dut&startitems=1&enditems=10.
6-10-24 15:04:27 : Dbg : GET /setupapp/denon/asp/func/dynamOD.asp?ex45v=0005CD2B126E&id=592.
6-10-24 15:04:27 : Dbg : Temporary test redirect to: http://mp3.ffh.de/ffhchannels/hqeurodance.mp3.
6-10-24 15:04:28 : Dbg : GET /setupapp/denon/asp/func/dynamOD.asp?ex45v=0005CD2B126E&id=592.
6-10-24 15:04:28 : Dbg : Temporary test redirect to: http://mp3.ffh.de/ffhchannels/hqeurodance.mp3.
```

I can now use version 1.2.3 as well!

**Comment by TheBossME** [comment]
What do we learn about that situation ?

A proper stations.ini or stations.yaml would solve lot's of issues.

I,do recommend using the stations.ini or yaml file before adding own channels into the list.

But sometimes the AVR's are stupid.
I have also issues with the stations.yaml file while starting with ytuner. Some of the issues are ytuner related but most of them are User issue. That's normal, we are humans. 

Great Sunday evening !

**Comment by coffeegreg** [comment]
>Hah nice debug surprise :-)
I can now use version 1.2.3 as well!

Does this mean you see the full menu where you can select stations and listen to them? :smiley:

**Comment by Stijn-Daniels** [comment]
> > Hah nice debug surprise :-)
> > I can now use version 1.2.3 as well!
> 
> Does this mean you see the full menu where you can select categories and stations and listen to them? 😃

Yes it shows my stations as well as browsing through all stations. And the full menu ofcourse. 

I don’t think it was a not working skyradio link. When i remove the dns redirect it works, and a second channel that i could still play had the exact same issues. 

anyways, your fix of “changing the channel” did the trick

**Comment by coffeegreg** [comment]
I'm glad to know that YTuner works for you. :smiley: 
Read carefully the description in README.MD and in `ytuner.ini` and `avr.ini`. You may discover interesting functionalities. :+1: 

>When i remove the dns redirect it works

I don't really understand what "dns redirect" is all about. :thinking:  Could you write something more? Your experiences and observations may help others someday.

**Comment by Stijn-Daniels** [comment]
> I'm glad to know that YTuner works for you. 😃 Read carefully the description in README.MD and in `ytuner.ini` and `avr.ini`. You may discover interesting functionalities. 👍
> 
> > When i remove the dns redirect it works
> 
> I don't really understand what "dns redirect" is all about. 🤔 Could you write something more? Your experiences and observations may help others someday.

I meant removing the entry on my DNS provider (adguard) that points denon.vtuner.com to the ytuner server. So when the Denon is allowed to access the internet directly it succeeds in playing the skyradio channel. But when i add the DNS rewrite that points the traffic to Ytuner we got in the above situation. Which you managed to fix!

**Comment by coffeegreg** [comment]
Please let me know when you finish testing YTuner with AVR-2313.
I'll be happy to add your Denon to the "Confirmed working" list. :rocket:

**Comment by TheBossME** [comment]
The issue needs to be clarified. It looks like a dns setup issue in general.

Have you set the dns redirection before powering the AVR to the network ?. My AVR has buffered settings on the Network interface.

Please do the following while using dns redirection.

If you have set the vtuner redirection check for backup dns entries your device is using like primary.vtuner.com and secondary.vtuner.com.

Check with dnslookup for <denon>.vtuner.com 

I'm using dns redirect for Yamaha on pihole and on adguard and it worked fine while analyzed the vtuner ip addresses for Yamaha devices

Here are my entries for pihole and adguard. Greg, It could be part of the documentation, while some other guys needs redirection.

![image](https://github.com/user-attachments/assets/1ea58c96-bb6d-40af-ba01-363dc8d5bfd6)

![image](https://github.com/user-attachments/assets/e2ba0a99-05d1-48ac-9c2d-43da79c8630e)

**Comment by coffeegreg** [comment]
Bea... yes, you right. This case need more clarification. :+1: 
It seems to me that we understand the word "redirect" differently here.
I tell you what I have done with my test case scenrio and latest test YTuner release :

This log entry:
>6-10-24 07:47:08 : Dbg : Unknown route : GET /setupapp/denon/asp/func/dynamOD.asp?ex45v=0005CD2B126E&id=592

means that the AVR is trying to connect to the radio station whose URL points exactly to... the YTuner machine. :open_mouth: 
And here we can see how differently YTuner and the original vTuner work.
The YTuner sends real radio stations link to the AVR like this one :
`http://mp3.ffh.de/ffhchannels/hqeurodance.mp3`
but vTuner sends to the AVR someting like this :
`http://radio567.vtuner.com/setupapp/denon/asp/func/dynamOD.asp?ex45v=0005CD2B126E&id=592`
... and when vTuner service get such request from AVR it does a HTTP 302 redirect to:
`http://25453.live.streamtheworld.com/SKYRADIO.mp3?dist=vtuner`
and AVR will start play a music. (Try it with your web browser :wink: )
But what happens when YTuner receives a link like this one:
`http://radio567.vtuner.com/setupapp/denon/asp/func/dynamOD.asp?ex45v=0005CD2B126E&id=592` ?
... nothing, because YTuner does not support such endpoint and this log entry appear:
>6-10-24 07:47:08 : Dbg : **Unknown route** : GET /setupapp/denon/asp/func/dynamOD.asp?ex45v=0005CD2B126E&id=592

So to "cure" our Denon I made a temporary endpoint supporting the following URI part: `func/dynamOD.asp.` and make redirection (HTTP 302) to any corrent radio station link like `http://mp3.ffh.de/ffhchannels/hqeurodance.mp3`.
Yup.. From now on, Denon is "cured" because the last radio station it plays uses the real link, not the vTuner's URL used for later redirection. :wink:

:thinking:  An approach such as that used by vTuner may prove to be better. If a radio station URL changes and someone/something at vTuner monitors it and quickly updates the data about the URL change in its radio station database the user will not even know about this change because his AVR will still use the same link which will only redirect him to the right one. Yeah, solution "good" enough to "block" some AVRs too... :wink: 

Therefore I believe that the whole case has nothing to do with DNS configuration. :wink: 

BTW... What is wrong with YTuner's built-in DNS service? :thinking: Why do you use additional services such as dnsmasq, pihole or adguard? :thinking:

**Comment by Stijn-Daniels** [comment]
Hey Greg, everything is working as it should, better then before! So feel to mark it as  comfirmed. 

The only caveat is that the issue i had is generic for this Denon type? But if that ever happens the solution is in the thread!

**Comment by Stijn-Daniels** [comment]
@TheBossME i meant DNS rewrite, my adguard setup looks exactly the same (with different ip ;-) )

> BTW... What is wrong with YTuner's built-in DNS service? 🤔 Why do you use additional services such as dnsmasq, pihole or adguard? 🤔

I use adguard for filtering ads on my entire network, so mobile phones, laptop, computer. Saves us from a lot of commercials. And it offers functionality to redirect the DNS to Ytuner, so why not use it.
