### ISSUE TITLE
DNS Server error: Could not bind socket.

### ISSUE THREAD

**Issue by SimonBard** [coffeegreg/YTuner#39]
Many thanks for the development of the application. When starting it on my rpi, I encounter the following error:

```
$ sudo ./ytuner
YTuner v1.2.4 Copyright (c) 2024 Greg P. (https://github.com/coffeegreg)
1-12-24 20:46:02 : Inf : Starting services...
1-12-24 20:46:02 : Err : CheckMyStationsThread Error: Unable to open file "/home/manfred/Downloads/ytuner124-docker/config/stations.ini": No such file or directory.
1-12-24 20:46:02 : Inf : Checking local database.
1-12-24 20:46:02 : Inf : Local database is ready.
1-12-24 20:46:02 : Err : DNS Server error: Could not bind socket..
1-12-24 20:46:02 : Inf : Web Service: listening on: 192.168.178.176:80.
```

There is no other application blocking the port:
```
$ sudo netstat -tnlp | grep :80
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      3612314/docker-prox
tcp6       0      0 :::8080                 :::*                    LISTEN      3612321/docker-prox
```

**Comment by TheBossME** [comment]
systemd-resolver running on Port 53 ?

Please type ss -tulpn and post result please.

**Comment by TheBossME** [comment]
Port 53 is used by systemd resolver actually.

you can easily stop systemd-resolver if you didn't use that.

systemctl stop systemd-resolved
Systemctl disable systemd-resolved

also you can remove it. 

apt purge systemd-resolved

**Comment by coffeegreg** [comment]
>$ sudo netstat -tnlp | grep :53
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      702/systemd-resolve

As you can see systemd-resolved listening on UDP 53 port.
I'm not sure and I have no way to check it right now :thinking:  .. try this :
```
  sudo systemctl disable systemd-resolved.service
  sudo systemctl stop systemd-resolved
```
place `dns=default` line in the [main] section of your `/etc/NetworkManager/NetworkManager.conf`
`mv /etc/resolv.conf /etc/resolv.conf.del`
`sudo service network-manager restart` or `sudo systemctl restart NetworkManager.service` :thinking: 
Beatrice .. can you confirm this ? :thinking:

**Comment by TheBossME** [comment]
What OS is used actually ?. Debian ?
Then purge systemd-resolver

**Comment by coffeegreg** [comment]
Closed due to inactivity.
