### ISSUE TITLE
stations.yaml issue while scrolling

### ISSUE THREAD

**Issue by TheBossME** [coffeegreg/YTuner#8]
Hi Greg, 

I have discovered a small problem in the stations.yaml. I have not yet verified it in detail. 

However, it seems that my AVR cannot be scrolled to the end of a collection of radio stations if one of the stations in the list is not currently broadcasting. 

There is no way to determine beforehand in the station list whether the link is broken. I had 2 such cases in my station list, after removing from the list it was possible to scroll to the end again.

I didn't see that as application issue. But was interested to see that.

**Comment by coffeegreg** [comment]
I have never experienced this behavior with my AVRs. Sometimes it happens that when browsing the contents of Radio-browser stations, some of them do not broadcast or broadcast in an unsupported format, but this never causes the problems you described. I can continue browsing the station list without any problems. Strange behavior ... :thinking: 
You can place a sample of such a file here and I will be able to check it.

**Comment by coffeegreg** [comment]
@TheBossME 
Does this behavior still occur? Isn't this related to this https://github.com/coffeegreg/YTuner/issues/11 even though this issue concerns to `stations.yaml` and not radio-browser stations.

**Comment by TheBossME** [comment]
Fixed
