### ISSUE TITLE
404 on Windows 11

### ISSUE THREAD

**Issue by Larsvb0** [coffeegreg/YTuner#9]
Tried to install both x32 and x64 package. Both give me 404 errors. It runs fine and listens on port 80 (changed to 8090 as well). Disabled firewall but http(s)://ip:port gives me a 404.

any thoughts?

**Comment by TheBossME** [comment]
Please change loglevel to debug and sent the results.

**Comment by Larsvb0** [comment]
YTuner v1.0.2 Copyright (c) 2023 Greg P. (https://github.com/coffeegreg)
11-12-2023 15:13:34 : Inf : Starting services...
11-12-2023 15:13:34 : Inf : Loading RB UUIDs cache file.
11-12-2023 15:13:34 : Inf : Successfully loaded 43425 RB UUIDs from cache file.
11-12-2023 15:13:34 : Inf : Successfully loaded 10 my stations.
11-12-2023 15:13:34 : Inf : Web server listening on: 10.0.0.196:8090.
11-12-2023 15:13:56 : Dbg : Unknown route : GET /.
11-12-2023 15:14:49 : Dbg : Unknown route : GET /.
11-12-2023 15:14:50 : Dbg : Unknown route : GET /.
11-12-2023 15:14:50 : Dbg : Unknown route : GET /.
11-12-2023 15:14:51 : Dbg : Unknown route : GET /.

**Comment by TheBossME** [comment]
Have you set debug to level 4 ?

YTuner v1.0.2 Copyright (c) 2023 Greg P. (https://github.com/coffeegreg)
11-12-23 18:07:17 : Inf : Starting services...
11-12-23 18:07:17 : Inf : Loading RB UUIDs cache file.
11-12-23 18:07:18 : Inf : Successfully loaded 43424 RB UUIDs from cache file.
11-12-23 18:07:18 : Inf : Successfully loaded 629 my stations.
11-12-23 18:07:18 : Inf : DNS server listening on: 10.10.100.240:53.
11-12-23 18:07:18 : Inf : Web server listening on: 10.10-100.240:80.
11-12-23 18:07:18 : Inf : AVRs HTTP requests IP target:

It should like like that:

**Comment by TheBossME** [comment]
did not see port 53 enabled on your machine

Are you sure using port 8090 web port for your receiver ?

Most of the radios cannot change the default port 80.

Please set your static dns on the receiver to your host and port 80 (default)

I think you're goin failed with your setup.

When using different dns server, you need use dnsmasq the dns entries.

I recommend using static settings on your receiver address all to your host where ytuner is running on.

**Comment by Larsvb0** [comment]
that Ycast was an old browser url. 

I defaulted to port 80 and all works now. Mystation works as well.

YTuner v1.0.2 Copyright (c) 2023 Greg P. (https://github.com/coffeegreg)
11-12-2023 20:11:28 : Inf : Starting services...
11-12-2023 20:11:28 : Inf : Loading RB UUIDs cache file.
11-12-2023 20:11:28 : Inf : Successfully loaded 43425 RB UUIDs from cache file.
11-12-2023 20:11:28 : Inf : Successfully loaded 10 my stations.
11-12-2023 20:11:28 : Inf : DNS server listening on: 10.0.0.196:53.
11-12-2023 20:11:28 : Inf : Web server listening on: 10.0.0.196:80.
11-12-2023 20:11:55 : Dbg : DNS Query intercept : denon.vtuner.com.
11-12-2023 20:11:55 : Dbg : GET /setupapp/denon/asp/BrowseXML/loginXML.asp?token=0.
11-12-2023 20:11:55 : Dbg : GET /setupapp/denon/asp/browsexm2/loginXML.asp?mac=6599DCBBF03940D650CFF54376B1B8FF&fver=1.754333&dlang=eng&startitems=1&enditems=10.
11-12-2023 20:11:55 : Dbg : GET /setupapp/denon/asp/browsexm2/loginXML.asp?mac=6599DCBBF03940D650CFF54376B1B8FF&fver=1.754333&dlang=eng&startitems=1&enditems=10.
11-12-2023 20:12:04 : Dbg : GET /ytuner/my_stations?ytuner=true&mac=6599DCBBF03940D650CFF54376B1B8FF&fver=1.754333&dlang=eng&startitems=1&enditems=10.
11-12-2023 20:12:07 : Dbg : GET /ytuner/my_stations/Dance?ytuner=true&mac=6599DCBBF03940D650CFF54376B1B8FF&fver=1.754333&dlang=eng&startitems=1&enditems=10.
11-12-2023 20:12:14 : Dbg : GET /ytuner/my_stations/Dance?ytuner=true&mac=6599DCBBF03940D650CFF54376B1B8FF&fver=1.754333&dlang=eng&startitems=1&enditems=10.
11-12-2023 20:12:17 : Dbg : GET /ytuner/my_stations/Rock?ytuner=true&mac=6599DCBBF03940D650CFF54376B1B8FF&fver=1.754333&dlang=eng&startitems=1&enditems=10.
11-12-2023 20:12:21 : Dbg : GET /ytuner/my_stations?ytuner=true&mac=6599DCBBF03940D650CFF54376B1B8FF&fver=1.754333&dlang=eng&startitems=1&enditems=10.

thanks for your help!

**Comment by coffeegreg** [comment]
**_Beatrice, you are the best_**. :clap:
Thank you for your support to other YTuner users. :thumbsup:
Sorry, I was away for a long time. In the meantime, I try to find an interesting job, but out of luck so far. Still trying...
Nevertheless, I found some time to prepare a new version of YTuner (v1.1.0).
Maybe today or in the next few days there will be a new version of YTuner. I'm testing it right now. Perhaps this new version of YTuner will appear today or in a few days. I added filtering and sorting as you suggested and most important ... I added caching. Now YTuner works ultra fast :rocket: without unnecessary waiting for every response from radio-browser.info and YTuner executable file is still below 2 MB.
I also added a few more improvements, functionalities and a few fixes... hang on ... :smile:

**Comment by coffeegreg** [comment]
@Larsvb0 :
May I add your Denon AVR-X3200W to "Confirmed working" list ?

**Comment by TheBossME** [comment]
Greg. What kind of job are you interested in ?
Maybe I can help.

**Comment by coffeegreg** [comment]
Ho.. ho.. ho... Here is Santa Claus. :santa: 
I heard that Beatrice is a very good and kind girl and I have the latest release of YTuner for her. :gift: 
For all other girls and boys too... even less polite than Beatrice. :smile: 
I'm getting out of here because the elves are messing with my sleigh. Ho.. ho.. ho.. :santa:

**Comment by TheBossME** [comment]
Good morning Greg,

Application improvements sounds good 👍 
But, application in linux x64/86 is actually Version 1.0.2 

Please check.

And one question. Is version 1.1.0 looking into the config subdirectory to get settings ?

I will take a look into arm64 binary today and will come back if I see similar.

🙋‍♀️ ho ho 
Have a nice day

**Comment by coffeegreg** [comment]
Good morning Bea,
Yes, You're right. Yesterday I spent almost the whole day making changes in YTuner and I was a little bit tired at the end of the day and... I 've got the wrong directory with the versions to prepare release. :wink: 
Fixed now :+1: Thanks for your vigilance.
Yes, I decided to move all configuration files to the `config` subdirectory. The Stations.ini/yaml files and optional bookmark files should be automatically moved to `config` when YTuner starts.
Please test the arm/aarch64 platform if you can and let me know what you think about the speed of YTuner in the new release :smile: 

Einen schönen Tag noch. :ok_hand:

**Comment by coffeegreg** [comment]
I think I can close this issue.
